<?php
$dbPath = getenv('DB_PATH') ?: __DIR__.'/database.db';
try {$db=new PDO('sqlite:'.$dbPath); $db->setAttribute(PDO::ATTR_ERRMODE,PDO::ERRMODE_EXCEPTION);} catch(Exception $e){http_response_code(500);die('Database unavailable: '.htmlspecialchars($e->getMessage()));}
function setting($k,$d=''){global $db;$s=$db->prepare('SELECT value FROM settings WHERE key=?');$s->execute([$k]);$v=$s->fetchColumn();return $v===false?$d:$v;}
function esc($v){return htmlspecialchars((string)$v,ENT_QUOTES,'UTF-8');}
$name=setting('site_name','AURA FFX');$desc=setting('site_description','');$logo=setting('logo_url','');$primary=setting('primary_color','#00e5ff');$secondary=setting('secondary_color','#3a86ff');$bg=setting('bg_color','#030b16');
$versions=$db->query('SELECT * FROM versions WHERE enabled=1 ORDER BY sort_order,id')->fetchAll(PDO::FETCH_ASSOC);
$projects=$db->query('SELECT * FROM projects WHERE enabled=1 ORDER BY id DESC')->fetchAll(PDO::FETCH_ASSOC);
$socials=$db->query('SELECT * FROM socials WHERE enabled=1 ORDER BY id')->fetchAll(PDO::FETCH_ASSOC);
$resources=$db->query('SELECT r.*,v.name version_name FROM resources r LEFT JOIN versions v ON v.id=r.version_id WHERE r.enabled=1 ORDER BY r.id DESC')->fetchAll(PDO::FETCH_ASSOC);
$rgb='0,229,255'; if(preg_match('/^#([0-9a-f]{6})$/i',$primary,$m)){ $rgb=hexdec(substr($m[1],0,2)).','.hexdec(substr($m[1],2,2)).','.hexdec(substr($m[1],4,2)); }
?><!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title><?=esc($name)?></title><link rel="icon" href="<?=esc($logo)?>"><link rel="preconnect" href="https://fonts.googleapis.com"><link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;600;700;800&family=Orbitron:wght@700;900&display=swap" rel="stylesheet"><style>
:root{--bg:<?=esc($bg)?>;--primary:<?=esc($primary)?>;--secondary:<?=esc($secondary)?>;--rgb:<?=$rgb?>;--muted:#8b949e;--surface:#071321}*{box-sizing:border-box}body{margin:0;background:radial-gradient(circle at 15% 20%,rgba(var(--rgb),.09),transparent 28%),radial-gradient(circle at 85% 50%,rgba(58,134,255,.09),transparent 30%),var(--bg);color:#f0f6fc;font-family:Inter,Arial;min-height:100vh}nav{position:sticky;top:0;z-index:10;background:rgba(3,11,22,.86);backdrop-filter:blur(14px);border-bottom:1px solid rgba(var(--rgb),.18);padding:13px 5%;display:flex;align-items:center}.logo{display:flex;align-items:center;gap:12px;font-family:Orbitron;font-weight:900;letter-spacing:2px}.logo img{width:52px;height:52px;border-radius:50%;object-fit:cover;border:2px solid rgba(var(--rgb),.4);box-shadow:0 0 20px rgba(var(--rgb),.25)}main{max-width:1100px;margin:auto;padding:70px 20px}.hero{text-align:center;min-height:55vh;display:flex;flex-direction:column;align-items:center;justify-content:center}.hero img{width:90px;height:90px;border-radius:50%;object-fit:cover;box-shadow:0 0 45px rgba(var(--rgb),.3);border:2px solid var(--primary)}h1{font:900 clamp(2.5rem,7vw,5rem) Orbitron;margin:22px 0 12px;background:linear-gradient(135deg,#fff,var(--primary));-webkit-background-clip:text;color:transparent}.hero p{max-width:650px;color:var(--muted);line-height:1.7}.btn{display:inline-block;margin:18px 8px;padding:13px 22px;border-radius:12px;text-decoration:none;font-weight:800;color:#001018;background:var(--primary);box-shadow:0 0 22px rgba(var(--rgb),.3)}.section{margin:70px 0}.title{text-align:center;font:900 1.35rem Orbitron;color:var(--primary);letter-spacing:2px;margin-bottom:25px}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(250px,1fr));gap:15px}.card{background:linear-gradient(145deg,rgba(10,25,47,.82),rgba(2,7,15,.9));border:1px solid rgba(var(--rgb),.15);border-radius:20px;padding:22px;box-shadow:0 20px 45px #0008;transition:.25s}.card:hover{transform:translateY(-5px);border-color:rgba(var(--rgb),.5)}.card h3{margin:0 0 8px}.card p{color:var(--muted);font-size:.92rem;line-height:1.5}.card a{color:var(--primary);text-decoration:none;font-weight:800}.socials{display:flex;justify-content:center;gap:14px;flex-wrap:wrap}.socials a{padding:12px 18px;border:1px solid rgba(var(--rgb),.2);border-radius:999px;color:#fff;text-decoration:none;background:#050f1d}.resource{display:flex;gap:15px;align-items:center}.icon{width:46px;height:46px;border-radius:14px;display:grid;place-items:center;background:rgba(var(--rgb),.1);color:var(--primary);font-weight:900}.notice{padding:12px;text-align:center;color:var(--muted);font-size:.85rem}footer{text-align:center;color:#66717d;padding:40px 20px;border-top:1px solid rgba(var(--rgb),.1)}@media(max-width:600px){main{padding:30px 14px}.hero{min-height:62vh}.grid{grid-template-columns:1fr}}
</style></head><body><nav><div class="logo"><img src="<?=esc($logo)?>"><span><?=esc($name)?></span></div></nav><div class="notice">Dynamic website • Managed from Telegram Admin Panel</div><main><section class="hero"><img src="<?=esc($logo)?>" alt="Logo"><h1><?=esc($name)?></h1><p><?=esc($desc)?></p><?php if(setting('main_download')): ?><a class="btn" href="<?=esc(setting('main_download'))?>" target="_blank">MAIN DOWNLOAD</a><?php endif; ?></section>
<section class="section"><div class="title">VERSIONS</div><div class="grid"><?php foreach($versions as $v): ?><div class="card"><h3><?=esc($v['name'])?></h3><p><?=esc($v['description'])?></p><a href="#resources" onclick="filterVersion(<?=json_encode($v['id'])?>)">VIEW →</a></div><?php endforeach; ?></div></section>
<section class="section" id="resources"><div class="title">RESOURCES</div><div class="grid"><?php if(!$resources): ?><div class="card"><p>No resources added yet. Add them from Telegram Admin.</p></div><?php endif; ?><?php foreach($resources as $r): ?><div class="card resource" data-version="<?=esc($r['version_id'])?>"><div class="icon"><?=esc(substr($r['icon'],0,5))?></div><div><h3><?=esc($r['name'])?></h3><p><?=esc($r['description'])?></p><a href="<?=esc($r['url'])?>" target="_blank">OPEN →</a></div></div><?php endforeach; ?></div></section>
<section class="section"><div class="title">REVIEW PROJECTS</div><div class="grid"><?php foreach($projects as $p): ?><div class="card"><h3><?=esc($p['name'])?></h3><p><?=esc($p['description'])?></p><a href="<?=esc($p['url'])?>" target="_blank">OPEN →</a></div><?php endforeach; ?></div></section>
<section class="section"><div class="title">CONNECT</div><div class="socials"><?php foreach($socials as $s): ?><a href="<?=esc($s['url'])?>" target="_blank"><?=esc($s['name'])?></a><?php endforeach; ?></div></section></main><footer><?=esc($name)?> • Powered by Telegram Admin</footer><script>function filterVersion(id){document.querySelectorAll('[data-version]').forEach(x=>x.style.display=(x.dataset.version==id?'flex':'none'));document.getElementById('resources').scrollIntoView({behavior:'smooth'})}</script></body></html>
